In [2]:
import pandas as pd
import re

# Membaca file CSV
data = pd.read_csv("combined_cleaned_data.csv")

# Menampilkan informasi tentang dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51391 entries, 0 to 51390
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   author        47569 non-null  object
 1   content       51391 non-null  object
 2   keyword       51391 non-null  object
 3   link          51391 non-null  object
 4   publish_date  51391 non-null  object
 5   source        51391 non-null  object
 6   title         51375 non-null  object
dtypes: object(7)
memory usage: 2.7+ MB

In [3]:
df = pd.DataFrame(data)
df.head()

,author,content,keyword,link,publish_date,source,title
0,NaN,"judul: author: Nonetanggal: Selasa, 01 Septe...",ekonomi yogyakarta,https://nasional.kontan.co.id/news/jokowi-bali...,2020-09-01 12:28:00,kontan.co.id,NaN
1,NaN,judul: Ekonomi Yogyakarta Dinilai Membaik Mesk...,ekonomi yogyakarta,https://regional.kontan.co.id/news/ekonomi-yog...,2022-12-29 18:50:00,kontan.co.id,Ekonomi Yogyakarta Dinilai Membaik Meski Upah ...
2,NaN,"judul: Di tengah pandemi, geliat ekonomi digit...",ekonomi yogyakarta,https://regional.kontan.co.id/news/di-tengah-p...,2021-06-01 20:38:00,kontan.co.id,"Di tengah pandemi, geliat ekonomi digital di Y..."
3,Oleh :\n\n\nDera Fitri,VIVA – PT Homliv Anugerah Tritunggal Indonesia...,ekonomi yogyakarta,https://www.viva.co.id/bisnis/1721077-ekspor-p...,2024-06-07 16:26:00,viva.co.id,Ekspor Produk Kayu Yogyakarta Membuka Peluang ...
4,Oleh :\n\n\nHarry Siswoyo,VIVA.co.idBaca Juga : Menanti Pintu Ger...,ekonomi yogyakarta,https://www.viva.co.id/berita/nasional/625551-...,2015-05-13 17:01:00,viva.co.id,"Sabda Raja Berpolemik, Ratu Denmark Kunjungi K..."

In [4]:
# Konversi kolom publish_date ke datetime
data['publish_date'] = pd.to_datetime(data['publish_date'], errors='coerce')

# Tentukan rentang waktu
start_date = pd.to_datetime("2020-01-01")
end_date = pd.to_datetime("2024-12-31")

# Tentukan keyword
keyword = ["ekonomi yogyakarta","inflasi yogyakarta","perdagangan yogyakarta","pariwisata yogyakarta"]

# Gabungkan keyword dengan regex
regex_pattern = '|'.join(keyword)

# Filter data berdasarkan rentang waktu dan keyword
filtered_data = data[
    (data['publish_date'] >= start_date) &
    (data['publish_date'] <= end_date) &
    (data['keyword'].str.contains(regex_pattern, case=False, na=False))
]

# Tampilkan data yang telah difilter
print(filtered_data)

                                                  author  \
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                 Oleh :\n\n\nDera Fitri
5      Oleh :\n\n\nFikri Halim,\n                    ...
...                                                  ...
48519                        Adji G Rinepta - detikJogja
48520                    Rista Rama Dhany - detikFinance
48521                           Indra Komara - detikBali
48522                  Virgina Maulita Putri - detikInet
48523                    Anindya Milagsita - detikJateng

                                                 content  \
0      judul: author: Nonetanggal:   Selasa, 01 Septe...
1      judul: Ekonomi Yogyakarta Dinilai Membaik Mesk...
2      judul: Di tengah pandemi, geliat ekonomi digit...
3      VIVA – PT Homliv Anugerah Tritunggal Indonesia...
5      VIVA – Menteri Dalam Negeri (Mendagri) Tito Ka...
...                                                  ...
48519  Daftar Isi Kota Jogja  Sleman  Bantul  Kulon P...
48520  Jakarta - Dolar Amerika Serikat (AS) pada perd...
48521  Jakarta - Mantan calon presiden (capres) Anies...
48522  Jakarta - Setelah beberapa hari bungkam, otori...
48523  Daftar Isi\r30 Contoh Soal Sejarah Kelas 11 Se...

                      keyword  \
0          ekonomi yogyakarta
1          ekonomi yogyakarta
2          ekonomi yogyakarta
3          ekonomi yogyakarta
5          ekonomi yogyakarta
...                       ...
48519  perdagangan yogyakarta
48520  perdagangan yogyakarta
48521  perdagangan yogyakarta
48522  perdagangan yogyakarta
48523  perdagangan yogyakarta

                                                    link        publish_date  \
0      https://nasional.kontan.co.id/news/jokowi-bali... 2020-09-01 12:28:00
1      https://regional.kontan.co.id/news/ekonomi-yog... 2022-12-29 18:50:00
2      https://regional.kontan.co.id/news/di-tengah-p... 2021-06-01 20:38:00
3      https://www.viva.co.id/bisnis/1721077-ekspor-p... 2024-06-07 16:26:00
5      https://www.viva.co.id/bisnis/1419169-ekonomi-... 2021-11-01 23:18:00
...                                                  ...                 ...
48519  https://www.detik.com/jogja/berita/d-7582531/p... 2024-10-11 08:20:00
48520  https://finance.detik.com/bursa-dan-valas/d-74... 2024-07-19 09:17:00
48521  https://www.detik.com/bali/hukum-dan-kriminal/... 2024-10-30 14:46:00
48522  https://inet.detik.com/cyberlife/d-7511795/pen... 2024-08-27 22:00:00
48523  https://www.detik.com/jateng/berita/d-7555858/... 2024-09-24 15:00:00

             source                                              title
0      kontan.co.id                                                NaN
1      kontan.co.id  Ekonomi Yogyakarta Dinilai Membaik Meski Upah ...
2      kontan.co.id  Di tengah pandemi, geliat ekonomi digital di Y...
3        viva.co.id  Ekspor Produk Kayu Yogyakarta Membuka Peluang ...
5        viva.co.id  Ekonomi Yogyakarta Tumbuh 11,8 Persen, Mendagr...
...             ...                                                ...
48519     detik.com  \n Prakiraan Cuaca DIY Hari Ini: Jogja-Bantul ...
48520     detik.com  \r\n        Dolar AS Pagi Ini Perkasa di Rp 16...
48521     detik.com  \n        Pesan Menyentuh Anies ke Tom Lembong...
48522     detik.com  \n                                    Pengadil...
48523     detik.com  \n        30 Contoh Soal Sejarah Kelas 11 Seme...

[21288 rows x 7 columns]

In [5]:
filtered_data.head()

,author,content,keyword,link,publish_date,source,title
0,NaN,"judul: author: Nonetanggal: Selasa, 01 Septe...",ekonomi yogyakarta,https://nasional.kontan.co.id/news/jokowi-bali...,2020-09-01 12:28:00,kontan.co.id,NaN
1,NaN,judul: Ekonomi Yogyakarta Dinilai Membaik Mesk...,ekonomi yogyakarta,https://regional.kontan.co.id/news/ekonomi-yog...,2022-12-29 18:50:00,kontan.co.id,Ekonomi Yogyakarta Dinilai Membaik Meski Upah ...
2,NaN,"judul: Di tengah pandemi, geliat ekonomi digit...",ekonomi yogyakarta,https://regional.kontan.co.id/news/di-tengah-p...,2021-06-01 20:38:00,kontan.co.id,"Di tengah pandemi, geliat ekonomi digital di Y..."
3,Oleh :\n\n\nDera Fitri,VIVA – PT Homliv Anugerah Tritunggal Indonesia...,ekonomi yogyakarta,https://www.viva.co.id/bisnis/1721077-ekspor-p...,2024-06-07 16:26:00,viva.co.id,Ekspor Produk Kayu Yogyakarta Membuka Peluang ...
5,"Oleh :\n\n\nFikri Halim,\n ...",VIVA – Menteri Dalam Negeri (Mendagri) Tito Ka...,ekonomi yogyakarta,https://www.viva.co.id/bisnis/1419169-ekonomi-...,2021-11-01 23:18:00,viva.co.id,"Ekonomi Yogyakarta Tumbuh 11,8 Persen, Mendagr..."

In [6]:
# Menyimpan hasil bersih ke file baru
filtered_data.to_csv("data_filtered_baru.csv", index=False)

In [7]:
df = pd.DataFrame(filtered_data)

In [8]:
# Mengonversi kolom 'Tanggal Terbit' menjadi tipe datetime
df['publish_date'] = pd.to_datetime(df['publish_date'], format='%Y-%m-%d %H:%M:%S')

# Membuat kolom 'Month' untuk periode bulanan
df['Period'] = df['publish_date'].dt.to_period('M')

# Memisahkan bulan dan tahun menjadi kolom terpisah
df['Bulan'] = df['publish_date'].dt.month
df['Tahun'] = df['publish_date'].dt.year

# Menampilkan DataFrame
df.head()

,author,content,keyword,link,publish_date,source,title,Period,Bulan,Tahun
0,NaN,"judul: author: Nonetanggal: Selasa, 01 Septe...",ekonomi yogyakarta,https://nasional.kontan.co.id/news/jokowi-bali...,2020-09-01 12:28:00,kontan.co.id,NaN,2020-09,9,2020
1,NaN,judul: Ekonomi Yogyakarta Dinilai Membaik Mesk...,ekonomi yogyakarta,https://regional.kontan.co.id/news/ekonomi-yog...,2022-12-29 18:50:00,kontan.co.id,Ekonomi Yogyakarta Dinilai Membaik Meski Upah ...,2022-12,12,2022
2,NaN,"judul: Di tengah pandemi, geliat ekonomi digit...",ekonomi yogyakarta,https://regional.kontan.co.id/news/di-tengah-p...,2021-06-01 20:38:00,kontan.co.id,"Di tengah pandemi, geliat ekonomi digital di Y...",2021-06,6,2021
3,Oleh :\n\n\nDera Fitri,VIVA – PT Homliv Anugerah Tritunggal Indonesia...,ekonomi yogyakarta,https://www.viva.co.id/bisnis/1721077-ekspor-p...,2024-06-07 16:26:00,viva.co.id,Ekspor Produk Kayu Yogyakarta Membuka Peluang ...,2024-06,6,2024
5,"Oleh :\n\n\nFikri Halim,\n ...",VIVA – Menteri Dalam Negeri (Mendagri) Tito Ka...,ekonomi yogyakarta,https://www.viva.co.id/bisnis/1419169-ekonomi-...,2021-11-01 23:18:00,viva.co.id,"Ekonomi Yogyakarta Tumbuh 11,8 Persen, Mendagr...",2021-11,11,2021

In [9]:
# Fungsi untuk menghapus nama kota dan penerbit
def remove_city_and_publisher(text):
    # Pola regex untuk mendeteksi nama kota dan penerbit di awal teks
    pattern = r'^\w+,\s+\w+\s'
    # Menghapus pola tersebut dari teks
    cleaned_text = re.sub(pattern, '', text)
    return cleaned_text

# Terapkan pada kolom 'Deskripsi'
df['content'] = df['content'].apply(remove_city_and_publisher)

In [10]:
# Fungsi untuk membersihkan teks ulasan
def cleaningtext(text):
    text = re.sub(r'@[A-Za-z0-9]+', ' ', text)  # Menghapus @mentions
    text = re.sub(r'#[A-Za-z0-9]+', ' ', text)  # Menghapus hashtags
    text = re.sub(r"http\S+|www\S+|https\S+", ' ', text, flags=re.MULTILINE)  # Menghapus URL
    text = re.sub(r'[0-9]+', ' ', text)  # Menghapus angka
    text = re.sub(r'\n', ' ', text)  # Menghapus baris baru
    text = re.sub(r"[-()\"#/@;:<>{}'+=~|.!?,_]", " ", text)  # Menghapus karakter khusus
    text = re.sub(r'[^\x00-\x7F]+', ' ', text) # Menghapus karakter non-ASCII (untuk Unicode yang tidak diinginkan)
    text = re.sub(r'\s+', ' ', text) #Menghapus spasi ganda dan memastikannya hanya ada satu spasi
    text = text.strip()  # Menghapus spasi di awal dan akhir
    return text  # Pastikan return di dalam fungsi

# Menerapkan preprocessing pada kolom 'Clean_Text'
df['Clean_Text'] = df['content'].apply(cleaningtext)

# Menampilkan hasil beberapa kolom yang sudah dibersihkan
print(df[['Clean_Text']])

                                              Clean_Text
0      judul author Nonetanggal Selasa September WIB ...
1      judul Ekonomi Yogyakarta Dinilai Membaik Meski...
2      judul Di tengah pandemi geliat ekonomi digital...
3      VIVA PT Homliv Anugerah Tritunggal Indonesia d...
5      VIVA Menteri Dalam Negeri Mendagri Tito Karnav...
...                                                  ...
48519  Daftar Isi Kota Jogja Sleman Bantul Kulon Prog...
48520  Jakarta Dolar Amerika Serikat AS pada perdagan...
48521  Jakarta Mantan calon presiden capres Anies Bas...
48522  Jakarta Setelah beberapa hari bungkam otoritas...
48523  Daftar Isi Contoh Soal Sejarah Kelas Semester ...

[21288 rows x 1 columns]

In [11]:
# Fungsi untuk merubah teks menjadi lowercase
def casefoldingText(text):
    text = text.lower()
    return text

# Menerapkan fungsi casefoldingText pada kolom '3/Lebih' dari dataframe df
df['Clean_Text'] = df['Clean_Text'].apply(casefoldingText)

# Menampilkan hasil perubahan lowercase
print(df[['Clean_Text']])

                                              Clean_Text
0      judul author nonetanggal selasa september wib ...
1      judul ekonomi yogyakarta dinilai membaik meski...
2      judul di tengah pandemi geliat ekonomi digital...
3      viva pt homliv anugerah tritunggal indonesia d...
5      viva menteri dalam negeri mendagri tito karnav...
...                                                  ...
48519  daftar isi kota jogja sleman bantul kulon prog...
48520  jakarta dolar amerika serikat as pada perdagan...
48521  jakarta mantan calon presiden capres anies bas...
48522  jakarta setelah beberapa hari bungkam otoritas...
48523  daftar isi contoh soal sejarah kelas semester ...

[21288 rows x 1 columns]

In [12]:
# Fungsi untuk menghapus kata-kata yang terlalu pendek
def hapus_kata_pendek(teks, batas_panjang=2):
    # Tokenisasi teks menjadi kata-kata
    kata_kata = teks.split()
    # Menghapus kata-kata yang panjangnya kurang dari batas_panjang
    kata_kata_bersih = [kata for kata in kata_kata if len(kata) >= batas_panjang]
    return ' '.join(kata_kata_bersih)

# Fungsi untuk menghapus kalimat yang tidak relevan
def hapus_kalimat_tidak_relevan(teks):
    # Hapus kalimat yang hanya berisi karakter non-alfabet atau terlalu pendek
    if not teks or len(teks.split()) < 2:
        return ''
    return teks

# Menerapkan fungsi ke dalam DataFrame
df['Clean_Text'] = df['Clean_Text'].apply(hapus_kata_pendek)  # Menghapus kata-kata pendek
df['Clean_Text'] = df['Clean_Text'].apply(hapus_kalimat_tidak_relevan)  # Menghapus kalimat yang tidak relevan

# Menampilkan hasil
print(df[['Clean_Text']])

                                              Clean_Text
0      judul author nonetanggal selasa september wib ...
1      judul ekonomi yogyakarta dinilai membaik meski...
2      judul di tengah pandemi geliat ekonomi digital...
3      viva pt homliv anugerah tritunggal indonesia d...
5      viva menteri dalam negeri mendagri tito karnav...
...                                                  ...
48519  daftar isi kota jogja sleman bantul kulon prog...
48520  jakarta dolar amerika serikat as pada perdagan...
48521  jakarta mantan calon presiden capres anies bas...
48522  jakarta setelah beberapa hari bungkam otoritas...
48523  daftar isi contoh soal sejarah kelas semester ...

[21288 rows x 1 columns]

In [13]:
import nltk
from nltk.tokenize import word_tokenize

# Fungsi untuk membaca stopwords dari file
def load_stopwords(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        stopwords = file.read().splitlines()  # Membaca setiap baris sebagai stopword
    return set(stopwords)

# Path ke file stopwords
stopwords_path = r'C:\Users\asus\Documents\MUH RIFAI\Tugas Akhir\TA1\stopwords.indo.txt'

# Memuat stopwords dari file
stopwords_indonesia = load_stopwords(stopwords_path)

# Menambahkan kata-kata tambahan ke dalam stopwords
additional_stopwords = {'dengan', 'untuk','jadi'}
stopwords_indonesia.update(additional_stopwords)

# Fungsi untuk menghapus stopwords dari teks
def hapus_stopwords(teks, stopwords):
    # Tokenisasi teks
    kata_kata = word_tokenize(teks)
    # Menghapus stopwords
    kata_kata_bersih = [kata for kata in kata_kata if kata not in stopwords]
    # Gabungkan token menjadi string kembali
    return ' '.join(kata_kata_bersih)

# Terapkan penghapusan stopwords pada kolom 'Clean_Text' di dataframe
df['Clean_Text'] = df['Clean_Text'].apply(lambda x: hapus_stopwords(x, stopwords_indonesia))

# Menampilkan hasil setelah penghapusan stopwords
print(df[['Clean_Text']])

                                              Clean_Text
0      judul author nonetanggal selasa september wib ...
1      judul ekonomi yogyakarta dinilai membaik upah ...
2      judul tengah pandemi geliat ekonomi digital yo...
3      viva pt homliv anugerah tritunggal indonesia p...
5      viva menteri negeri mendagri tito karnavian be...
...                                                  ...
48519  daftar isi kota jogja sleman bantul kulon prog...
48520  jakarta dolar amerika serikat as perdagangan p...
48521  jakarta mantan calon presiden capres anies bas...
48522  jakarta hari bungkam otoritas prancis buka sua...
48523  daftar isi contoh soal sejarah kelas semester ...

[21288 rows x 1 columns]

In [14]:
import re

# Path ke file slangwords.txt
kamus_slang_path = r'C:\Users\asus\Documents\MUH RIFAI\Tugas Akhir\TA1\slangwords.txt'

# Kamus Typo yang sudah Anda buat
kamus_typo = {
    'yg': 'yang', 'rp':'rupiah','ga': 'tidak', 'gak': 'tidak', 'gk': 'tidak', 'tdk': 'tidak',
    'dlm': 'dalam', 'sm': 'sama', 'klo': 'kalau', 'aja': 'saja', 'dr': 'dari',
    'trs': 'terus', 'tp': 'tapi', 'udh': 'sudah', 'jg': 'juga', 'blm': 'belum',
    'sy': 'saya', 'aku': 'saya', 'km': 'kamu', 'lg': 'lagi', 'bnr': 'benar',
    'bs': 'bisa', 'hrs': 'harus', 'msh': 'masih', 'org': 'orang', 'skrg': 'sekarang',
    'ny': 'nya', 'knp': 'kenapa', 'gmna': 'bagaimana', 'pdhl': 'padahal',
    'smg': 'semoga', 'krn': 'karena', 'mlh': 'malah', 'ntr': 'nanti', 'sdh': 'sudah',
    'bgmn': 'bagaimana', 'tlg': 'tolong', 'banget': 'sangat', 'mau': 'ingin',
    'kasih': 'beri', 'seler': 'penjual', 'makasih': 'terima kasih',
    'btw': 'ngomong-ngomong', 'brg': 'barang', 'jd': 'jadi', 'bgt': 'sangat',
    'dmn': 'di mana', 'nggak': 'tidak', 'ajaib': 'menakjubkan', 'amanah': 'dapat dipercaya',
    'pokoknya': 'intinya', 'keren': 'luar biasa', 'mantap': 'hebat', 'ajib': 'menakjubkan',
    'kece': 'menarik', 'cuan': 'keuntungan', 'ribet': 'rumit', 'copot': 'terlepas',
    'lapor': 'melapor', 'cepet': 'cepat', 'capek': 'lelah', 'sblm': 'sebelum',
    'trm': 'terima', 'gampang': 'mudah', 'lumayan': 'cukup', 'ane': 'saya',
    'agan': 'bapak/ibu', 'gt': 'gitu', 'dng': 'dengan', 'trimakasih': 'terima kasih',
    'gmn': 'bagaimana', 'udah': 'sudah', 'jir': 'anjir', 'janggan': 'jangan',
    'ama': 'sama', 'bosok': 'busuk', 'hadeuhh': 'aduh','pt':'perusahaan','to':'untuk','with':'dengan'
}

# Membaca file slangwords.txt dan mengonversinya menjadi kamus
def load_slang(kamus_slang_path):
    kamus_slang = {}
    with open(kamus_slang_path, 'r', encoding='utf-8') as file:
        for line in file:
            if '=>' in line:
                slang, baku = line.strip().split('=>')
                kamus_slang[slang.strip()] = baku.strip()
    return kamus_slang

# Load kamus slang
kamus_slang = load_slang(kamus_slang_path)

# Fungsi untuk mengganti slang dengan bentuk baku
def ubah_slang(teks, kamus_slang):
    words = teks.split()
    processed_words = [kamus_slang.get(word, word) for word in words]
    return ' '.join(processed_words)

# Fungsi untuk memperbaiki typo
def perbaiki_typo(teks, kamus_typo):
    words = teks.split()
    processed_words = [kamus_typo.get(word, word) for word in words]
    return ' '.join(processed_words)

# Gabungkan keduanya: slang dan typo correction
def normalisasi_teks(teks, kamus_slang, kamus_typo):
    teks = ubah_slang(teks, kamus_slang)  # Ganti slang
    teks = perbaiki_typo(teks, kamus_typo)  # Perbaiki typo
    return teks

# Terapkan normalisasi pada kolom 'Clean_Text' di dataframe
df['Clean_Text'] = df['Clean_Text'].apply(lambda x: normalisasi_teks(x, kamus_slang, kamus_typo))

# Menampilkan hasil setelah penghapusan slang dan typo correction
print(df[['Clean_Text']])

                                              Clean_Text
0      judul author nonetanggal selasa september wib ...
1      judul ekonomi yogyakarta dinilai membaik upah ...
2      judul tengah pandemi geliat ekonomi digital yo...
3      viva perusahaan homliv anugerah tritunggal ind...
5      viva menteri negeri mendagri tito karnavian be...
...                                                  ...
48519  daftar isi kota jogja sleman bantul kulon prog...
48520  jakarta dolar amerika serikat as perdagangan p...
48521  jakarta mantan calon presiden capres anies bas...
48522  jakarta hari bungkam otoritas prancis buka sua...
48523  daftar isi contoh soal sejarah kelas semester ...

[21288 rows x 1 columns]

In [15]:
import nltk
from nltk.tokenize import word_tokenize

# Download resource yang dibutuhkan (coba hanya sekali)
nltk.download('punkt')

# Fungsi tokenisasi menggunakan NLTK
def tokenisasi(teks):
    # Tokenisasi menggunakan word_tokenize dari NLTK
    return word_tokenize(teks)

# Menggunakan metode tokenisasi pada DataFrame
df['Tokens'] = df['Clean_Text'].apply(tokenisasi)

# Menampilkan hasil tokenisasi
print(df[['Clean_Text', 'Tokens']])

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\asus\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

                                              Clean_Text  \
0      judul author nonetanggal selasa september wib ...
1      judul ekonomi yogyakarta dinilai membaik upah ...
2      judul tengah pandemi geliat ekonomi digital yo...
3      viva perusahaan homliv anugerah tritunggal ind...
5      viva menteri negeri mendagri tito karnavian be...
...                                                  ...
48519  daftar isi kota jogja sleman bantul kulon prog...
48520  jakarta dolar amerika serikat as perdagangan p...
48521  jakarta mantan calon presiden capres anies bas...
48522  jakarta hari bungkam otoritas prancis buka sua...
48523  daftar isi contoh soal sejarah kelas semester ...

                                                  Tokens
0      [judul, author, nonetanggal, selasa, september...
1      [judul, ekonomi, yogyakarta, dinilai, membaik,...
2      [judul, tengah, pandemi, geliat, ekonomi, digi...
3      [viva, perusahaan, homliv, anugerah, tritungga...
5      [viva, menteri, negeri, mendagri, tito, karnav...
...                                                  ...
48519  [daftar, isi, kota, jogja, sleman, bantul, kul...
48520  [jakarta, dolar, amerika, serikat, as, perdaga...
48521  [jakarta, mantan, calon, presiden, capres, ani...
48522  [jakarta, hari, bungkam, otoritas, prancis, bu...
48523  [daftar, isi, contoh, soal, sejarah, kelas, se...

[21288 rows x 2 columns]

In [16]:
!pip install Sastrawi

Requirement already satisfied: Sastrawi in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (1.0.1)

In [ ]:
from multiprocessing import Pool
import os

# Fungsi untuk stemming
def stemming(tokens):
    return ' '.join([stemmer.stem(token) for token in tokens])

# Fungsi pembantu untuk multiprocessing
def preprocess_row(tokens):
    return stemming(tokens)

# Terapkan multiprocessing untuk stemming
if __name__ == '__main__':
    with Pool(os.cpu_count()) as pool:
        df['Stemmed_Text'] = pool.map(preprocess_row, df['Tokens'])
    
    # Tampilkan hasil
    print(df[['Clean_Text', 'Tokens', 'Stemmed_Text']])

In [ ]:
df.head()

In [ ]:
df.to_csv('Data_Prepro.csv', index=False)